# http://localhost:3001/post


# POST http://localhost:3001/post
# content-type: application/json

# {
#     "title": "test title2",
#     "postText": "testPost",
#     "username": "testuser"
# }

# http://localhost:3001/test/1


//comments Post
# POST http://localhost:3001/comments
# Content-Type: application/json

# {
#     "commentBody": "test comment",
#     "PostId": 4
# }


//comment Get

http://localhost:3001/comments/4
